### PR TITLE
Can't assign I18NexFsBackend to NewableModule<BackendModule>

### PR DESCRIPTION
**Pull request by miniplus**
Solves #32

#### Checklist

- [x] only relevant code is changed (make a diff before you submit the PR)
- [x] run tests `npm run test`
- [x] tests are included
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

#### Checklist (for documentation change)

- [x] only relevant documentation part is changed (make a diff before you submit the PR)
- [x] motivation/reason is provided
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/i18next/.github/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by adrai** [comment]
@pedrodurek ok for you?

**Comment by adrai** [comment]
will merge now, but would love if @pedrodurek could check for the general types usage in collaboration with the i18next plugins

**Comment by adrai** [comment]
included in v2.0.1

**Comment by pedrodurek** [comment]
Sorry @adrai, I wasn't close to my computer in the last couple of days, it looks great to me!

**Pull request merged**
